-- 코드를 작성해주세요
SELECT G3.ID
FROM ECOLI_DATA AS G1  # 1세대
JOIN ECOLI_DATA AS G2 ON G1.ID = G2.PARENT_ID # 2세대
JOIN ECOLI_DATA AS G3 ON G2.ID = G3.PARENT_ID # 3세대
WHERE G1.PARENT_ID IS NULL
ORDER BY G3.ID ASC;