# RECURSIVE - 자기 자신을 참조
WITH RECURSIVE CTE AS (
    SELECT ID, 1 AS GENERATION -- 1세대에서 시작
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, CTE.GENERATION + 1 -- 세대 +1씩 증가
    FROM ECOLI_DATA E
    JOIN CTE ON E.PARENT_ID = CTE.ID -- 이전 세대의 자식 찾기
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE
WHERE CTE.ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;